// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgdncciriipkiqbesgsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnZG5jY2lyaWlwa2lxYmVzZ3NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDEwNjIsImV4cCI6MjA3MjcxNzA2Mn0.le4ttokknVl5NzGgrXJRp-9_Bj9jh30R3q716U1pEXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});